{
  "openapi": "3.0.1",
  "info": {
    "title": "47-alpha.1-【git-回归测试-默认模块】备份sub",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "宠物"
    }
  ],
  "paths": {
    "/branch1/api1": {
      "get": {
        "summary": "branch1 新建接口1",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 0,
                      "description": "状态码"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Pet",
                      "description": "宠物信息"
                    }
                  },
                  "required": [
                    "code",
                    "data"
                  ]
                },
                "example": {
                  "code": 0,
                  "data": {
                    "name": "Hello Kity",
                    "photoUrls": [
                      "http://dummyimage.com/400x400"
                    ],
                    "id": 3,
                    "category": {
                      "id": 71,
                      "name": "Cat"
                    },
                    "tags": [
                      {
                        "id": 22,
                        "name": "Cat"
                      }
                    ],
                    "status": "sold"
                  }
                }
              }
            },
            "headers": {}
          },
          "400": {
            "$ref": "#/components/responses/参数不正确",
            "description": ""
          }
        },
        "security": []
      }
    },
    "/ref/other_module/1": {
      "get": {
        "summary": "/ref/other_module/1 Copy",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/M2-schema1"
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/M2-schema1"
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/ref/current_module/2": {
      "get": {
        "summary": "/ref/current_module/2",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Tag"
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pet"
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/pet/{petId}": {
      "get": {
        "summary": "查询宠物详情-branch1&关联",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "description": "宠物 ID",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 0,
                      "description": "状态码"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Pet",
                      "description": "宠物信息"
                    }
                  },
                  "required": [
                    "code",
                    "data"
                  ]
                },
                "example": {
                  "code": 0,
                  "data": {
                    "name": "Hello Kity",
                    "photoUrls": [
                      "http://dummyimage.com/400x400"
                    ],
                    "id": 3,
                    "category": {
                      "id": 71,
                      "name": "Cat"
                    },
                    "tags": [
                      {
                        "id": 22,
                        "name": "Cat"
                      }
                    ],
                    "status": "sold"
                  }
                }
              }
            },
            "headers": {}
          },
          "400": {
            "$ref": "#/components/responses/参数不正确",
            "description": ""
          }
        },
        "security": []
      },
      "delete": {
        "summary": "删除宠物信息",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "description": "Pet id to delete",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "api_key",
            "in": "header",
            "description": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 0
                    }
                  },
                  "required": [
                    "code"
                  ]
                },
                "example": {
                  "code": 0
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/pet": {
      "post": {
        "summary": "新建宠物信息",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "description": "宠物名",
                    "example": "Hello Kitty",
                    "type": "string"
                  },
                  "status": {
                    "description": "宠物销售状态",
                    "example": "sold",
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "status"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 0
                    },
                    "data": {
                      "$ref": "#/components/schemas/Pet"
                    }
                  },
                  "required": [
                    "code",
                    "data"
                  ]
                },
                "example": {
                  "code": 0,
                  "data": {
                    "name": "Hello Kity",
                    "photoUrls": [
                      "http://dummyimage.com/400x400"
                    ],
                    "id": 3,
                    "category": {
                      "id": 71,
                      "name": "Cat"
                    },
                    "tags": [
                      {
                        "id": 22,
                        "name": "Cat"
                      }
                    ],
                    "status": "sold"
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "put": {
        "summary": "修改宠物信息",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Pet"
                    }
                  },
                  "required": [
                    "code",
                    "data"
                  ]
                },
                "example": {
                  "code": 0,
                  "data": {
                    "name": "Hello Kity",
                    "photoUrls": [
                      "http://dummyimage.com/400x400"
                    ],
                    "id": 3,
                    "category": {
                      "id": 71,
                      "name": "Cat"
                    },
                    "tags": [
                      {
                        "id": 22,
                        "name": "Cat"
                      }
                    ],
                    "status": "sold"
                  }
                }
              }
            },
            "headers": {}
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          },
          "405": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/pet/findByStatus": {
      "get": {
        "summary": "根据状态查找宠物列表",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "description": "Status values that need to be considered for filter",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Pet"
                  }
                },
                "example": {
                  "code": 0,
                  "data": [
                    {
                      "name": "Hello Kity",
                      "photoUrls": [
                        "http://dummyimage.com/400x400"
                      ],
                      "id": 3,
                      "category": {
                        "id": 71,
                        "name": "Cat"
                      },
                      "tags": [
                        {
                          "id": 22,
                          "name": "Cat"
                        }
                      ],
                      "status": "sold"
                    },
                    {
                      "name": "White Dog",
                      "photoUrls": [
                        "http://dummyimage.com/400x400"
                      ],
                      "id": 3,
                      "category": {
                        "id": 71,
                        "name": "Dog"
                      },
                      "tags": [
                        {
                          "id": 22,
                          "name": "Dog"
                        }
                      ],
                      "status": "sold"
                    }
                  ]
                }
              }
            },
            "headers": {}
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "code"
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {
      "branchNewSchema1": {
        "required": [
          "name",
          "photoUrls",
          "id_branchModi",
          "category",
          "tags",
          "status"
        ],
        "type": "object",
        "properties": {
          "id_branchModi": {
            "type": "integer",
            "format": "int64",
            "minimum": 1,
            "description": "宠物ID编号"
          },
          "category": {
            "$ref": "#/components/schemas/Category",
            "description": "分组"
          },
          "name": {
            "type": "string",
            "description": "名称",
            "example": "doggie"
          },
          "photoUrls": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "照片URL"
          },
          "tags": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Tag"
            },
            "description": "标签"
          },
          "status": {
            "type": "string",
            "description": "宠物销售状态",
            "enum": [
              "available",
              "pending",
              "sold"
            ]
          }
        }
      },
      "Pet": {
        "required": [
          "name",
          "photoUrls",
          "id_branchModi",
          "category",
          "tags",
          "status"
        ],
        "type": "object",
        "properties": {
          "id_branchModi": {
            "type": "integer",
            "format": "int64",
            "minimum": 1,
            "description": "宠物ID编号"
          },
          "category": {
            "$ref": "#/components/schemas/Category",
            "description": "分组"
          },
          "name": {
            "type": "string",
            "description": "名称",
            "example": "doggie"
          },
          "photoUrls": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "照片URL"
          },
          "tags": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Tag"
            },
            "description": "标签"
          },
          "status": {
            "type": "string",
            "description": "宠物销售状态",
            "enum": [
              "available",
              "pending",
              "sold"
            ]
          }
        }
      },
      "Category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "minimum": 1,
            "description": "分组ID编号"
          },
          "name": {
            "type": "string",
            "description": "分组名称"
          }
        },
        "xml": {
          "name": "Category"
        }
      },
      "Tag": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "minimum": 1,
            "description": "标签ID编号"
          },
          "name": {
            "type": "string",
            "description": "标签名称"
          }
        },
        "xml": {
          "name": "Tag"
        }
      },
      "M2-schema1": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "ID 编号"
          },
          "M2-schema1": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "M2-schema1"
        ]
      }
    },
    "responses": {
      "M2_Resp1": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "title": "",
              "type": "object",
              "properties": {
                "M2_Resp1_item": {
                  "type": "string"
                },
                "id": {
                  "type": "string",
                  "description": "ID 编号"
                }
              },
              "required": [
                "M2_Resp1_item",
                "id"
              ]
            }
          }
        }
      },
      "参数不正确": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "message": {
                  "type": "string"
                }
              },
              "required": [
                "code",
                "message"
              ]
            }
          }
        }
      }
    },
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}